# Site settings
title: Huxpro
description: A clean and refined Jekyll theme.
header_img: /assets/img/home.jpeg
baseurl: /huxpro
owner: Lynn
published_at: 2020

# Sidebar settings
sidebar: true
sidebar_avatar: /assets/img/avatar.jpeg
sidebar_about_description: 以直觉和性情生存，<br>喜欢一切美丽的事物。

# SNS settings
RSS:                true
email:              lynn9388@gmail.com
github_username:    lynn9388
#zhihu_username:     lynn9388
#weibo_username:     lynn9388
#linkedin_username:  lynn9388
#twitter_username:   lynn9388
#facebook_username:  lynn9388

# Google Analytics settings (https://analytics.google.com/)
ga_measurement_id:

# Build settings
paginate: 10
timezone: Asia/Shanghai
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
collections:
  pages:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: _posts
    values:
      layout: post
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
