# Site settings
title: Huxpro
header-img: /assets/img/home-bg.jpg
description: Jekyll theme
baseurl: /huxpro
owner: Lynn
published_at: 2019

# Sidebar settings
sidebar: true
sidebar-about-description: For the next quantum leap<br>离开世界之前，一切都是过程
sidebar-avatar: /assets/img/avatar-hux-ny.jpg

# SNS settings
RSS: true
zhihu_username:     lynn9388
weibo_username:     lynn9388
linkedin_username:  lynn9388
#twitter_username:   lynn9388
#facebook_username:  lynn9388
github_username:    lynn9388

# Build settings
paginate: 10
timezone: Asia/Shanghai
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
