# Site settings
title: Huxpro
description: Jekyll theme
header_img: /assets/img/home-bg.jpg
baseurl: /huxpro
owner: Lynn
published_at: 2019

# Sidebar settings
sidebar: true
sidebar_avatar: /assets/img/avatar-hux-ny.jpg
sidebar_about_description: For the next quantum leap<br>离开世界之前，一切都是过程

# SNS settings
RSS: true
zhihu_username:     lynn9388
weibo_username:     lynn9388
linkedin_username:  lynn9388
#twitter_username:   lynn9388
#facebook_username:  lynn9388
github_username:    lynn9388

# Build settings
paginate: 10
timezone: Asia/Shanghai
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
collections:
  pages:
    output: true
    permalink: /:path/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
